#!/usr/bin/env bash

switchToWindow=4
wait_file=${HOME}/pause-clk-intrpt

function speak() {
  message="$*"
  if [[ $OSTYPE == "darwin"* ]]; then
    say -v Daniel "[[volm 0.5]] $message"
  elif [[ $OSTYPE == "linux"* ]]; then
    espeak -p 50 -s 120 -a 250 "$message"
  fi
}

function smile() {
# speak “Smile. It increases your face value.”
  speak “Smile”
}

function onoff() {
 local messagePrefix="$(date +'%H hours, %M minutes'): Switch context now or lose day mastery, control, productivity and wealth."
 local message="${messagePrefix} Turn it off"
 [[ $1 == "on" ]] && local message="${messagePrefix} Turn it on"
 speak "$message"
}

function beep() {
  beeps=${1:-5}
  for (( i=0; i<$beeps; i++ )); do
    tput bel
    sleep 0.225
  done
}

function lock_screen() {
  lockAfter=${1:-2}
  sleep $lockAfter
  if [[ $OSTYPE == "darwin"* ]]; then
    osascript mac-lock.scpt
  elif [[ $OSTYPE == "linux"* ]]; then
    xdg-screensaver lock
  fi
}

function show_stash() {
  [[ $(wc -c < /home/ncoder/.local/share/notes@maestroschan.fr/0_text) != 0 ]] && \
  wmctrl -s 1 && \
  gedit /home/ncoder/.local/share/notes@maestroschan.fr/0_text
}

function pause() {
  echo pause at $(date) >> ${wait_file}
  echo 'clk-intrpt paused'
}

function resume() {
  [[ -f ${wait_file} ]] && rm ${wait_file}
  echo 'clk-intrpt paused removed'
}

function kill-prev-skips() {
  pids=$(cat ${wait_file} | grep skip-pid | awk '{ print $2}')
  for pid in ${pids}; do
    kill ${pid}
  done
  rm ${wait_file}
}

function skip_break() {
  kill-prev-skips
  duration=${1:-330}
  echo 'skipping break'
  echo "skip-pid $$" >> ${wait_file}
  pause
  echo "wait for ${duration}s"
  sleep ${duration}
  resume
}

case ${1} in
    "pause")
	pause
	exit 0
	;;
    "resume")
	resume
	exit 0
        ;;
    "skip")
	shift
	skip_break ${1}
	exit 0
        ;;
    "dev")
	lock_screen
	exit 0
#	say dev
#	osascript mac-lock.scpt
        ;;
#    *)
#	;;
esac

clear
echo "###############################"
echo "#### Starting intrpt timer ####"
echo "###############################"

while true; do
  sleep 0.5
  if [[ -f ${wait_file} ]]; then
    continue
  fi

  time_val=$(date)
  echo -ne "\\r$time_val"

  time_min=$(echo $time_val | cut -d' ' -f 4)
  time_min=${time_min:3:5}
  if [[ $(egrep '(59:00|29:00)$' <(echo $time_min)) ]]; then
    echo ""
    echo "-------------------------------"
    onoff on 
    #show_stash &
    if [[ $OSTYPE == "darwin"* ]]; then
      killall ScreenSaverEngine
    elif [[ $OSTYPE == "linux"* ]]; then
     loginctl unlock-session
    fi
    beep 4
    sleep 1
  elif [[ $(egrep '(55:00|25:00)$' <(echo $time_min)) ]]; then
    echo ""
    echo "-------------------------------"
    onoff
    beep 8 &
    sleep 1
  elif [[ $(egrep '(26:30|27:00|27:30|28:00|28:30|56:30|57:00|57:30|58:00|58:30)$' <(echo $time_min)) ]]; then
    echo ""
    echo "-------------------------------"
    beep 4 &
    onoff
    lock_screen &
    sleep 1
    smile
  elif [[ $(egrep '(26:00|56:00)$' <(echo $time_min)) ]]; then
    echo ""
    echo "-------------------------------"
    #show_stash &
    beep 20 &
    lock_screen &
    sleep 1
  elif [[ $(egrep '00$' <(echo $time_min)) ]]; then
    smile
  fi
done

BB
