#!/usr/bin/env bash

switchToWindow=4
wait_file=${HOME}/pause-clk-intrpt

function onoff() {
 local messagePrefix="Balance Mastery: Stick to the calendar:"
 local message="${messagePrefix} Turn it off"
 [[ $1 == "on" ]] && local message="${messagePrefix} Turn it on"
 espeak -p 50 -s 120 -a 250 "$message"
}

function beep() {
  beeps=${1:-5}
  for (( i=0; i<$beeps; i++ )); do
    tput bel
    sleep 0.225
  done
}

function lock_screen() {
  lockAfter=${1:-2}
  sleep $lockAfter
  #wmctrl -s 5
  #sleep 20
  gnome-screensaver-command -l
}

function show_stash() {
  [[ $(wc -c < /home/ncoder/.local/share/notes@maestroschan.fr/0_text) != 0 ]] && \
  wmctrl -s 1 && \
  gedit /home/ncoder/.local/share/notes@maestroschan.fr/0_text
}

function pause() {
  date >> ${wait_file}
  echo 'clk-intrpt paused'
}

function resume() {
  [[ -f ${wait_file} ]] && rm ${wait_file}
  echo 'clk-intrpt paused removed'
}

echo $1
if [[ "${1}" = "pause" ]]; then
  pause
  exit 0
fi
if [[ "${1}" = "resume" ]]; then
  resume
  exit 0
fi

clear
echo "###############################"
echo "#### Starting intrpt timer ####"
echo "###############################"

while true; do
  sleep 0.5
  if [[ -f ${wait_file} ]]; then
    continue
  fi

  time_val=$(date)
  echo -ne "\\r$time_val"

  time_min=$(echo $time_val | cut -d' ' -f 5)
  time_min=${time_min:3:5}
  if [[ $(egrep '(59:00|29:00)$' <(echo $time_min)) ]]; then
    echo ""
    echo "-------------------------------"
    onoff on 
    show_stash &
    beep 12 &
    sleep 1
  fi
  if [[ $(egrep '(53:00|23:00)$' <(echo $time_min)) ]]; then
    echo ""
    echo "-------------------------------"
    onoff
    beep 8 &
    sleep 1
  fi
  if [[ $(egrep '(24:30|25:00|25:30|26:00|26:30|27:00|27:30|28:00|28:30|54:30|55:00|55:30|56:00|56:30|57:00|57:30|58:00|58:30)$' <(echo $time_min)) ]]; then
    echo ""
    echo "-------------------------------"
    beep 4 &
    lock_screen &
    sleep 1
  fi

  if [[ $(egrep '(24:00|54:00)$' <(echo $time_min)) ]]; then
    echo ""
    echo "-------------------------------"
    show_stash &
    beep 20 &
    lock_screen &
    sleep 1
  fi
done

