#!/usr/bin/env bash

switchToWindow=4

function beep() {
  beeps=${1:-5}
  for (( i=0; i<$beeps; i++ )); do
    tput bel
    sleep 0.225
  done
}

function lock_screen() {
  lockAfter=${1:-2}
  sleep $lockAfter
  #wmctrl -s 5
  #sleep 20
  gnome-screensaver-command -l
}

function show_stash() {
  [[ $(wc -c < /home/ncoder/.local/share/notes@maestroschan.fr/0_text) != 0 ]] && \
  wmctrl -s 1 && \
  gedit /home/ncoder/.local/share/notes@maestroschan.fr/0_text
}

function break_progress() {
  breakSeconds=${1:-60}
  for ((i=0;i<$breakSeconds;i+=10)); do
    sleep 10
    beep 2 &
  done;
}

function onoff() {
  local messagePrefix="Balance Mastery: Stick to the calendar:"
  local message="${messagePrefix} Turn it off"
  [[ $1 == on ]] && local message="${messagePrefix} Turn it on"
  espeak -p 50 -s 120 -a 250 "$message"
}

function balance() {
  echo "###############################"
  echo "#### Starting intrpt timer ####"
  echo "###############################"
  echo ""
  echo "Balance is timing, not intensity.

  It is not doing multiple tasks at 80%, but developing the skill of turning it on and turning it off.

  Sleep fully, then work intensely. Focus deeply, then relax completely. Give each phase your full attention.

  Balance is 'when to' not 'how to.'"

echo ""
echo "###############################"
}

clear
balance

while true; do

  sleep 0.5
  time_val=$(date)
  echo -ne "\\r$time_val"

  time_min=$(echo $time_val | cut -d' ' -f 5)
  time_min=${time_min:3:5}
  if [[ $(egrep '(14:00|29:00|44:00|59:00)$' <(echo $time_min)) ]]; then
    echo ""
    balance
    echo "-------------------------------"
    show_stash &
    beep 12 &
    onoff on
    sleep 1
  fi
  if [[ $(egrep '(11:50|26:50|41:50|56:50)$' <(echo $time_min)) ]]; then
    beep 4 &
    onoff
    sleep 1
  fi
  if [[ $(egrep '(12:00|27:00|42:00|57:00)$' <(echo $time_min)) ]]; then
    echo ""
    echo "-------------------------------"
    show_stash &
    beep 20 &
    break_progress 120 &
    lock_screen &
    sleep 1
  fi
  if [[ $(egrep '([0-5]5:00|[0-5]0:00)$' <(echo $time_min)) ]]; then
    echo ""
    echo "-------------------------------"
    beep 8
    sleep 1
  fi

done

