#! /usr/bin/env bash

session=wos

wmctrl -s 5
google-chrome --app="https://my.1password.com/home" > /dev/null 2>&1 &
sleep 4
/home/ncoder/.Nozbe/Nozbe > /dev/null 2>&1 &
#google-chrome --app="https://app.nozbe.com/#na/infobar" > /dev/null 2>&1 &
sleep 4
google-chrome --app="https://calendar.google.com/calendar/r" > /dev/null 2>&1 &
sleep 4
google-chrome --app="https://mail.google.com/mail/u/1/" > /dev/null 2>&1 &
sleep 4

wmctrl -s 11
#slack > /dev/null 2>&1 &
#sleep 4
google-chrome --app="https://open.spotify.com/" > /dev/null 2>&1 &
sleep 4
google-chrome --app="https://www.youtube.com/user/Computerphile/playlists"  > /dev/null 2>&1 &
sleep 4

wmctrl -s 4
google-chrome --app="https://app.ganttpro.com/#/list" > /dev/null 2>&1 &
sleep 4

wmctrl -s 3
google-chrome --app="https://www.evernote.com/Home.action?login=true#b=eee50092-a06a-4128-bea7-e2926ed7e176&ses=4&sh=1&sds=5&" > /dev/null 2>&1 &
sleep 4

wmctrl -s 9
klavaro > /dev/null 2>&1 &
google-chrome --app="https://thetypingcat.com/typing-speed-test/5m" > /dev/null 2>&1 &
sleep 4

wmctrl -s 8
google-chrome --app="https://learning.oreilly.com/home/" > /dev/null 2>&1 &
sleep 4

tmux start-server
tmux new-session -d -s $session -c ~ -n sigint 'clk15'
tmux new-window -c /home/ncoder/02_wos/jupyter-lab -n juptyr './run.sh'
sleep 4
wmctrl -s 0
google-chrome --new-window "https://github.com/" > /dev/null 2>&1 &
sleep 4
tmux new-window -c $GOPATH/src/github.com/openshift/ -n openshift
tmux attach-session -t $session

