apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ns-a
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ns-b
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: sa-1
  namespace: ns-a
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: role-a
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: rolebinding-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-a
subjects:
- kind: ServiceAccount
  name: sa1
  namespace: ns-a
